# Generated by Django 2.1 on 2019-03-25 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityAuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('CREATED', 'CREATED'), ('UPDATED', 'UPDATED'), ('DELETED', 'DELETED')], max_length=251, verbose_name='Operation Type')),
                ('fk_entity_id', models.PositiveIntegerField(db_column='fk_entity_id', verbose_name='Entity ID')),
                ('attribute', models.CharField(max_length=251, verbose_name='Field Name')),
                ('old_value', models.CharField(blank=True, db_column='old_value', max_length=251, null=True, verbose_name='Old Value')),
                ('new_value', models.CharField(blank=True, db_column='new_value', max_length=251, null=True, verbose_name='New Value')),
                ('comments', models.CharField(blank=True, db_column='comments', max_length=1019, null=True, verbose_name='Comments')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now_add=True, verbose_name='Updated On')),
                ('fm_entity_type', models.ForeignKey(db_column='fm_entity_id', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Entity Type')),
                ('performed_by', models.ForeignKey(blank=True, db_column='fk_performed_by_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Operation Performed By')),
            ],
            options={
                'verbose_name': 'Entity Audit Log',
                'verbose_name_plural': 'Entity Audit Logs',
                'db_table': 'entity_audit_log',
            },
        ),
    ]
