# Generated by Django 2.1 on 2019-04-02 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_auditor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entityauditlog',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='entityauditlog',
            name='attribute_type',
            field=models.CharField(default='None', max_length=251, verbose_name='Field Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entityauditlog',
            name='recorded_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Recorded On'),
            preserve_default=False,
        ),
    ]
